# Generated by Django 3.0.8 on 2020-07-08 16:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.CharField(default=uuid.UUID('533aa8ec-c13c-11ea-a362-0250343f333c'), max_length=50)),
                ('car_reg_no', models.CharField(max_length=50)),
                ('current_x', models.FloatField()),
                ('current_y', models.FloatField()),
                ('booked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=50)),
                ('rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ride_id', models.CharField(default=uuid.UUID('533af70e-c13c-11ea-8dee-0250343f333c'), max_length=50)),
                ('ride_start_time', models.DateTimeField(auto_now_add=True)),
                ('ride_end_time', models.DateTimeField()),
                ('start_x', models.FloatField(default=0.0)),
                ('start_y', models.FloatField(default=0.0)),
                ('end_x', models.FloatField(default=0.0)),
                ('end_y', models.FloatField(default=0.0)),
                ('user_name', models.CharField(blank=True, max_length=50)),
                ('fare', models.FloatField(default=0.0)),
                ('status', models.CharField(default='Available', max_length=50)),
                ('distance', models.FloatField(default=0.0)),
                ('timetaken', models.FloatField(blank=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ride.Car')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ride.Driver')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('rides', models.ManyToManyField(blank=True, null=True, to='ride.Ride')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ride.Driver'),
        ),
    ]
