# Generated by Django 3.0.8 on 2020-07-08 17:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='driver_mobile_no',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='car_id',
            field=models.CharField(default=uuid.UUID('a99c5392-c13d-11ea-903f-0250343f333c'), max_length=50),
        ),
        migrations.AlterField(
            model_name='ride',
            name='ride_id',
            field=models.CharField(default=uuid.UUID('a99c7aa3-c13d-11ea-a338-0250343f333c'), max_length=50),
        ),
    ]
