# Generated by Django 3.0.8 on 2020-07-08 18:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0002_auto_20200708_2238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='timetaken',
            new_name='estimated_time',
        ),
        migrations.AlterField(
            model_name='car',
            name='car_id',
            field=models.CharField(default=uuid.UUID('785fcc64-c145-11ea-b095-0250343f333c'), max_length=50),
        ),
        migrations.AlterField(
            model_name='ride',
            name='ride_end_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='ride_id',
            field=models.CharField(default=uuid.UUID('78601a85-c145-11ea-bb28-0250343f333c'), max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=uuid.UUID('786068a6-c145-11ea-93ca-0250343f333c'), max_length=50),
        ),
    ]
