# Generated by Django 3.0.8 on 2020-07-08 20:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0003_auto_20200708_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_id',
            field=models.CharField(default=uuid.UUID('76ffe5ed-c156-11ea-a037-0250343f333c'), max_length=50),
        ),
        migrations.AlterField(
            model_name='ride',
            name='ride_id',
            field=models.CharField(default=uuid.UUID('7700340e-c156-11ea-90e0-0250343f333c'), max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=uuid.UUID('7700d051-c156-11ea-bd7a-0250343f333c'), max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
