# Generated by Django 3.0.8 on 2020-07-08 20:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0004_auto_20200709_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_id',
            field=models.CharField(default=uuid.UUID('8ee50070-c156-11ea-a3ea-0250343f333c'), max_length=50),
        ),
        migrations.AlterField(
            model_name='ride',
            name='ride_id',
            field=models.CharField(default=uuid.UUID('8ee50071-c156-11ea-9b95-0250343f333c'), max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='rides',
            field=models.ManyToManyField(blank=True, to='ride.Ride'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=uuid.UUID('8ee50072-c156-11ea-aada-0250343f333c'), max_length=50),
        ),
    ]
